#!/usr/bin/env bash

OS_NAME=`uname -o 2>/dev/null || uname -s`

if [ $OS_NAME == "Msys" ]; then
	./tools/premake5.exe "$@"
elif [ $OS_NAME == "Darwin" ]; then
	./tools/premake5-mac "$@"
else
	./tools/premake5-linux "$@"
fi