name: Windows Build
on:
  push:
    branches: [ '**' ]  # Trigger on push to any branch
    tags: [ '**' ]      # Trigger on push of any tag

jobs:
  build:
    runs-on: windows-latest
    environment: default

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Test
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd test
          test